name: casa_inteligente
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.0.3
  flutter_launcher_icons: ^0.14.1
  animated_splash_screen: ^1.3.0
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  provider: ^6.1.2
  cloud_firestore: ^5.5.1
  firebase_database: ^11.2.0
  geolocator: ^13.0.2
  shared_preferences: ^2.3.4
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  theme_color: "#7f4867"
  min_sdk_android: 21
  adaptive_icon_background: "#7f4867" 
  adaptive_icon_foreground: "assets/icons/logo.png" 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo.png
