// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARyMN3zx0SmL4s3O5_JrIp7FqzD9efLQ0',
    appId: '1:1051929183501:web:17df6447cf6efc7ff7dc44',
    messagingSenderId: '1051929183501',
    projectId: 'casaqi200',
    authDomain: 'casaqi200.firebaseapp.com',
    storageBucket: 'casaqi200.firebasestorage.app',
    measurementId: 'G-7GPMPHF1PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe5lkmnRp0kDS6fCqDD-P2mZRJ3-c-fDU',
    appId: '1:1051929183501:android:28cc57be747ac08ff7dc44',
    messagingSenderId: '1051929183501',
    projectId: 'casaqi200',
    storageBucket: 'casaqi200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRr-Ot4AiuNrNYmXhEOS1k2hMTmfXAECs',
    appId: '1:1051929183501:ios:99a75cb2cae6f976f7dc44',
    messagingSenderId: '1051929183501',
    projectId: 'casaqi200',
    storageBucket: 'casaqi200.firebasestorage.app',
    iosBundleId: 'com.example.casaInteligente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRr-Ot4AiuNrNYmXhEOS1k2hMTmfXAECs',
    appId: '1:1051929183501:ios:99a75cb2cae6f976f7dc44',
    messagingSenderId: '1051929183501',
    projectId: 'casaqi200',
    storageBucket: 'casaqi200.firebasestorage.app',
    iosBundleId: 'com.example.casaInteligente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARyMN3zx0SmL4s3O5_JrIp7FqzD9efLQ0',
    appId: '1:1051929183501:web:4416c7713943c7e0f7dc44',
    messagingSenderId: '1051929183501',
    projectId: 'casaqi200',
    authDomain: 'casaqi200.firebaseapp.com',
    storageBucket: 'casaqi200.firebasestorage.app',
    measurementId: 'G-9M2NRFXT7N',
  );
}
